# Generated by Django 6.0.7 on 2026-07-12 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='situacao_cadastral',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Ativo', 'Ativo'), ('Inativo', 'Inativo'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=20),
        ),
    ]
