# Generated by Django 6.0.7 on 2026-07-09 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('condominio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=255)),
                ('telefone', models.CharField(max_length=18)),
                ('tipo_usuario', models.IntegerField(choices=[(1, 'Morador'), (2, 'Porteiro'), (3, 'Síndico')])),
                ('senha', models.CharField(max_length=255)),
                ('situacao_cadastral', models.CharField(max_length=50)),
                ('id_apartamento', models.ForeignKey(blank=True, db_column='id_apartamento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='condominio.apartamento')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
