# Generated by Django 6.0.7 on 2026-07-09 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloco',
            fields=[
                ('id_bloco', models.AutoField(primary_key=True, serialize=False)),
                ('bloco', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'bloco',
            },
        ),
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id_apartamento', models.AutoField(primary_key=True, serialize=False)),
                ('apartamento', models.IntegerField()),
                ('id_bloco', models.ForeignKey(db_column='id_bloco', on_delete=django.db.models.deletion.CASCADE, related_name='apartamentos', to='condominio.bloco')),
            ],
            options={
                'db_table': 'apartamento',
            },
        ),
    ]
