# Generated by Django 6.0.7 on 2026-07-09 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id_token', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'token',
            },
        ),
        migrations.CreateModel(
            name='Encomenda',
            fields=[
                ('id_encomendas', models.AutoField(primary_key=True, serialize=False)),
                ('data_recebimento', models.DateField()),
                ('hora_recebimento', models.TimeField()),
                ('retirar_urgencia', models.BooleanField(default=False)),
                ('codigo_rastreio', models.CharField(max_length=30)),
                ('quantidade', models.IntegerField(default=1)),
                ('observacao', models.CharField(blank=True, max_length=255, null=True)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='encomendas', to='authentication.usuario')),
                ('id_token', models.OneToOneField(db_column='id_token', on_delete=django.db.models.deletion.CASCADE, related_name='encomenda', to='encomendas.token')),
            ],
            options={
                'db_table': 'encomenda',
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id_notif', models.AutoField(primary_key=True, serialize=False)),
                ('mensagem', models.CharField(max_length=255)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('id_encomendas', models.ForeignKey(db_column='id_encomendas', on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='encomendas.encomenda')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='authentication.usuario')),
            ],
            options={
                'db_table': 'notificacao',
            },
        ),
        migrations.CreateModel(
            name='Retirada',
            fields=[
                ('id_retirada', models.AutoField(primary_key=True, serialize=False)),
                ('retirada_terceiros', models.CharField(blank=True, max_length=150, null=True)),
                ('hora_retirada', models.TimeField()),
                ('data_retirada', models.DateField()),
                ('id_encomendas', models.OneToOneField(db_column='id_encomendas', on_delete=django.db.models.deletion.CASCADE, related_name='retirada', to='encomendas.encomenda')),
            ],
            options={
                'db_table': 'retirada',
            },
        ),
    ]
