# Generated by Django 6.0.7 on 2026-07-11 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('encomendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encomenda',
            name='id_porteiro_cadastro',
            field=models.ForeignKey(blank=True, db_column='id_porteiro_cadastro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encomendas_cadastradas', to='authentication.usuario'),
        ),
    ]
