# Generated by Django 6.0.7 on 2026-07-11 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encomendas', '0002_encomenda_id_porteiro_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
